# Documentation:
# https://trovu.net/docs/users/advanced/#custom-configuration
namespaces:
- o
- it
- .it
- en
- .us
- de
- .de
- github: gdchilla
  name: my
defaultKeyword: qw
language: de
country: de
